### ISSUE TITLE
Can not interact with mentors page

### ISSUE THREAD

**Issue by kelledge** [devict/devict.org#101]
Once loaded, nothing on the page is clickable. All content -- including navigation, footers, etc. -- can not be interacted with.

Appears to only affect the mentors page.

When I get a moment I will attach a few more details.

**Comment by br0xen** [comment]
There appears to be a modal that isn't getting hidden on load:
`#contact-mentor-modal`

**Comment by kelledge** [comment]
Opened pull request to address the issue:

https://github.com/devict/devict.org/pull/102
