### ISSUE TITLE
Add a leadership page

### ISSUE THREAD

**Issue by jcbwlkr** [devict/devict.org#103]
Include 

* Board members with titles and profile pictures
* Anybody who runs an event. Again with profile pictures

**Comment by jcbwlkr** [comment]
This is done but there should also be contact information

**Comment by kentonh** [comment]
@jcbwlkr I'm going to take care of adding contact info, I'm assuming I should do so via the method that Mentors use? Should I convert the data/mentors.json file to include both Mentors and Board or would you rather a new data file be created?

**Comment by jcbwlkr** [comment]
Keep it simple. Just hard code stuff in the html. Ask people what they want
to share. For me it's my slack name and my phone number 316.461.1127

I dont expect everyone else to show all that
