### ISSUE TITLE
Explain how to compare "n" values in All Titles survey section

### ISSUE THREAD

**Issue by ccwoolfolk** [devict/devict.org#115]
We may want to add a note to the bottom of the first section explaining:
1) Why the sample size dropped from 190 in 2017 to 84 in 2018
2) Why the total n values for a given year don't match the sum of the n values in the years of experience tables (I suspect we didn't have years of experience data from some sources)

I can submit a PR with a fix but need help with the actual explanations.

<img width="1187" alt="Screenshot 2019-03-10 12 36 42" src="https://user-images.githubusercontent.com/20022270/54088980-bde6f880-4331-11e9-902c-a19b3bf64349.png">

**Comment by jcbwlkr** [comment]
@kentonh can you weigh in on this?
