### ISSUE TITLE
move "Sandip Southekal" to the former board member list

### ISSUE THREAD

**Issue by southekal** [devict/devict.org#127]
- `Sandip Southekal` has stepped down from the board starting 2020.
- Move profile found on `http://devict.org/about/` to the `Former Board Members` section

**Comment by jcbwlkr** [comment]
Same with `Jacob Walker`

**Comment by chrisl8** [comment]
Except we didn't actually vote to remove Sandip at the most recent board meeting. :-D

**Comment by jcbwlkr** [comment]
Votes aren't necessary unless a board member is being forcibly removed.
Sandip wrote in his resignation so he's off. We can't force someone to be
on the board lol

In my case really all I needed was an announcement but I appreciate that
y'all were thorough enough to vote on it anyway haha
