### ISSUE TITLE
bug: github signin URL not working

### ISSUE THREAD

**Issue by akebu6** [devict/devict.org#155]
the GitHub signin button the official page does not open instead it brings the following error: https://hacktoberfest.devict.org/auth/github/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=dZTRsd9wtOwWW4rkr50XkIFJRgbDH5ZUPotDYFUH7qP-OPw9Dgkl6wHm52AADr87hkdVG1XALS7brV6RCXjGIA%3D%3D

**Comment by sethetter** [comment]
You must be accessing the site from the old url. https://hacktoberfest.devict.org should work!

**Comment by akebu6** [comment]
Awesome, it works. Thanks!
