### ISSUE TITLE
Apply button hover effects dissappear after clicking

### ISSUE THREAD

**Issue by Aatmaj-Zephyr** [devict/devict.org#157]
### what is wrong?
Generally the apply button appears on hover. But when linke is pressed and we check again, the link corresponding to the button does not participate in the hover effect.

### how to reproduce the bug?
1) click on apply button
2) go back to the page 
3) hover over the job cards

### Screnshot

You can notice the underline is  missing because it appears only on hover
![image](https://github.com/devict/devict.org/assets/83284294/30095187-6c59-43e4-9538-4827b4d96c86)

_

![image](https://github.com/devict/devict.org/assets/83284294/32746c7c-a92a-451b-881f-5cffe1d42ec1)

**Comment by Aatmaj-Zephyr** [comment]
Can you please assign it to me for hacktober?

**Comment by sethetter** [comment]
@Aatmaj-Zephyr the screenshots you provided are for the [job board repo](https://github.com/devict/job-board), if you'd like to submit a PR there I'll keep an eye out for it.
