### ISSUE TITLE
Redesign the Homepage

### ISSUE THREAD

**Issue by sethetter** [devict/devict.org#20]
Does anyone agree that it would be a good idea to have some kind of quick info paragraph or even a single line description of what the group is on the homepage for first time visitors?

Should we include this? If so, where at and what should we say?

**Comment by jcbwlkr** [comment]
@bmodesign and I discussed some ideas for how to redesign the home page. Specifically we discussed moving from a three column layout to a taller one column layout with some kind of graphic accenting each section

**Comment by bmodesign** [comment]
I'll work on some artwork to help split the homepage up into 'stripes' that stair step down to 2 buttons, to join the community on Slack and to donate to keep the devICT machine running.

**Comment by jcbwlkr** [comment]
So this is pretty far underway so far. I know @bmodesign has talked about adding a banner graphic on there. Once that's done I think we'll close this issue and any future enhancements can be filed separately.

**Comment by chrisl8** [comment]
One year later: What is the status on this issue? Is it something to work on for 2017 Hacktoberfest, or is it ready to be closed?

**Comment by cjanzen** [comment]
Annnd yet another year ... :)

**Comment by jcbwlkr** [comment]
Let's call this one done :)
