### ISSUE TITLE
Event view for all upcoming / past events

### ISSUE THREAD

**Issue by sethetter** [devict/devict.org#29]
The home page shows the next most recent event, but it would be nice to have a view that shows all events, separated by upcoming / past.

**Comment by jcbwlkr** [comment]
In the Hugo version we no longer show events on the home page and we don't populate the event listing server side. We need to add some JS to the `/events` page to fetch the event listing from meetup and display it in some manner.

**Comment by jcbwlkr** [comment]
The url for events on meetup is on line 99 of https://github.com/devict/devict-hubot/blob/master/scripts/events.js

**Comment by MrsJaw** [comment]
Is this still an issue?

**Comment by jcbwlkr** [comment]
I'm gonna say no. We show upcoming events but not past. I'm fine with how it is.
