### ISSUE TITLE
URL for code challenge submissions instead of submission screen

### ISSUE THREAD

**Issue by sethetter** [devict/devict.org#30]
The submission area for the code challenges is nice an all, but Gist provides everything we need and more. It would make sense to remove the actual submission screen and instead store a gist link for each submission.

The URL provided could be arbitrary, that way someone can use another service like plnkr.co or jsbin.com as well.

If it is detected as a Gist or a GitHub repo we could do some special handling to actually grab the code and display it locally. As far as I am aware, GitHub/Gist have a very friendly API.

**Comment by jcbwlkr** [comment]
This feature no longer exists.
