### ISSUE TITLE
Should we switch from Foundation to Bootstrap?

### ISSUE THREAD

**Issue by sethetter** [devict/devict.org#50]
Every time I get in to make changes to layout I find myself unfamiliar with the CSS framework, currently it's Foundation. I think it'd be a good decision to switch to Bootstrap to increase the likelihood that someone contributing in the future will be familiar. It would also make things a bit easier on me :)

There aren't too many views in the site at the moment, so I don't think it would be a substantial task. Anyone up for it?

**Comment by mikeLspohn** [comment]
I'm down to help with this if no one else takes it on.

**Comment by sethetter** [comment]
@mikeLspohn do it! Fork the repo and submit a pull request. Then it can count towards your [Hacktoberfest](https://hacktoberfest.digitalocean.com) PR's :)

**Comment by jarrettgreen** [comment]
I can help as well. I'm a bootstrap master ;)

**Comment by sethetter** [comment]
Doooo iiiiit!

On Sun, Oct 11, 2015 at 6:53 PM Jarrett Green <notifications@github.com>
wrote:

> I can help as well. I'm a bootstrap master ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/devict/devict.org/issues/50#issuecomment-147256189>.
>
-- 
Regards,

Seth

**Comment by jcbwlkr** [comment]
This is happening in the redesign.
