### ISSUE TITLE
Donation / support page

### ISSUE THREAD

**Issue by sethetter** [devict/devict.org#55]
Right now we just have the button in the footer, which is good and should stay there. But having a full fledged donation / support page with info on why it's good to donate would be awesome.

**Comment by bmodesign** [comment]
I think it'd be nice to have a few of our new profile photos with a 'why devICT is awesome to me' short bio/text.... telling our story.

**Comment by jcbwlkr** [comment]
I think we should also move our Digital Ocean referral link here https://www.digitalocean.com/?refcode=0bc5d355b0fe

We're not hosted on Digital Ocean anymore so the old link location doesn't make sense.

**Comment by jcbwlkr** [comment]
This page has been updated with some JavaScript that gets both PayPal and Patreon donor information. It also includes a line item cost list (though it's not currently shown). I'd like to see this page show some kind of graphs comparing our costs to our donors. I'm thinking maybe like two stacked column charts like this

![image](https://cloud.githubusercontent.com/assets/2027263/18283949/7884a826-742d-11e6-91c2-c3ac5c91b7e8.png)

**Comment by jcbwlkr** [comment]
http://www.chartjs.org/ would probably be a good way to implement that. I would just use the CDN links to keep it simple.

**Comment by MrsJaw** [comment]
Is this still an issue?

**Comment by jcbwlkr** [comment]
Nah I'll go ahead and close. http://devict.org/support/ is a thing and it has the basic elements. Any efforts to improve that page are welcome but there's no specific action item right now.
