### ISSUE TITLE
Add mentorship pairing

### ISSUE THREAD

**Issue by jcbwlkr** [devict/devict.org#66]
We would like to start a program to pair up volunteer mentors with people needing their particular expertise.

To begin I have created a branch called `mentors` along with an empty page at `/mentors` and some sample data in `static/data/mentors.json`. That JSON file is served up at the url `/data/mentors.json` when `hugo server` is running.

My thought is that we could just update this json file as a simple "database" when we want to make changes then stick a little single page app on top of it and make it searchable by skill.

Here's the format right now for a mentor object
- `name`: The mentor's preferred name. Could be full name, just first name, a
  nickname, whatever.
- `username`: The mentor's slack username. My intent is the primary way of
  connecting with a mentor is to just message them on Slack.
- `avatar`: An optional URL for a profile picture of this user. I recommend
  Gravatar but whatever the mentor wants to use is fine. This field is optional
  so handle the case that it's missing.
- `skills`: An array of strings denoting the skills this mentor wants to teach.
  For example  `["go", "php", "api", "sql", "linux", "docker"]`
- `available`: A boolean flag that says if this mentor is accepting new
  mentees. Rather than enforcing some specific business rule on when a mentor
  is "taken" I figure we just leave it up to them to toggle this flag.

Here is what I would consider the MVP for this feature
- [x] Add some JS to the mentors page. This can be React, Angular 2, jQuery, or vanilla JavaScript if that's your thing. The site is already loading in jQuery and Bootstrap.js I believe so those are available. To include JS libraries just use a CDN and stick the urls in the `scripts` array of the TOML front-matter on `content/mentors.md`. For the JS you write yourself stick it in `static/js/mentors.js` and include `/js/mentors.js` as probably the last url in the `scripts` array.
- [x] Fetch and parse the JSON file then show a list of mentors. 
- [x] Hide the loading animation once the list is built
- [x] Provide an input field where users can search by skill.
- [x] Show the initial list of mentors in random order.
- [x] Somehow indicate the difference between available / unavailable mentors. Maybe unavailable mentors should not be included at all or maybe there is just a little footnote at the bottom of their names?

For inspiration check out this page https://php-mentoring.org/mentors

**Comment by jcbwlkr** [comment]
To clarify this is totally up for discussion. The issue as it's written now is my current vision but I'm open to changes.

**Comment by cjprieb** [comment]
My plan to start is to use Knockout to generate the HTML for displaying the list of mentors.

**Comment by jcbwlkr** [comment]
The basics of this feature are live. I'll file issues for additional features we want.
