### ISSUE TITLE
Mentors: You've found one but now what?

### ISSUE THREAD

**Issue by jcbwlkr** [devict/devict.org#74]
We have this UI that lists mentors and the skills they can teach. The copy on the page says to contact them by their username but I bet people could use a little more guidance.

Add a button on each mentor's card with some relevant font-awesome icon. When clicked it should pop up a modal with that mentor's picture and say something like:

```
Jacob Walker is available to mentor in these topics:

go, php, sql, docker, linux

To get started send them a message on Slack. Their username is jcbwlkr.

If you don't have an account on the devICT Slack then go here (https://devict-slackin.herokuapp.com/) and make one. It's free!
```

If the mentor is not available (`"available": false`) then maybe style the form like this

```
Jacob Walker is currently unavailable for mentorship.

They have indicated that they have expertise in these topics:

go, php, sql, docker, linux

They aren't taking on new mentees right now but they would certainly love to chat about those topics. Go ahead and give them a shout on Slack! Their username is jcbwlkr.

If you don't have an account on the devICT Slack then go here (https://devict-slackin.herokuapp.com/) and make one. It's free!
```

**Comment by cjprieb** [comment]
Should we add a link from their avatar/username to their slack profile as well? Such as "https://devict.slack.com/team/" + username? Then if they are part of slack, they can quickly start a private chat with them from the profile page.

**Comment by jcbwlkr** [comment]
:+1:
